- platform: flux
  name: Flux
  lights:
    - light.big_lamp
    - light.small_lamp
    - light.tv_lamp
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 2200
  start_time: '08:00'
  stop_time: '23:00'
  mode: mired
  disable_brightness_adjust: true
  transition: 10
  interval: 150
