#NUC
- platform: rest
  resource: http://192.168.0.4:8126/container/nodered
  name: NodeRed
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.4:8126/container/portainer
  name: Portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.4:8126/container/pihole
  name: PiHole
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.4:8126/container/mqtt
  name: MQTT
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.4:8126/container/syncthing
  name: Syncthing
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.4:8126/container/filebrowser
  name: FileBrowser
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

#NAS
- platform: rest
  resource: http://192.168.0.5:8126/container/transmission
  name: Transmission
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/jackett
  name: Jackett
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/sonarr
  name: Sonarr
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/radarr
  name: Radarr
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/plex
  name: Plex
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/ombi
  name: Ombi
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
- platform: rest
  resource: http://192.168.0.5:8126/container/bazarr
  name: Bazarr
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
