# - platform: template
#   switches:
#     washing_machine:
#       entity_id: switch.tplink
#       value_template: "{{ is_state('switch.tplink', 'on') }}"
#       turn_on:
#         service: switch.turn_on
#         entity_id: switch.tplink
#       turn_off:
#         service: switch.turn_off
#         entity_id: switch.tplink

- platform: template
  switches:
    tv:
      unique_id: "tv"
      friendly_name: TV
      icon_template: mdi:television
      entity_id: media_player.lg_webos_tv
      value_template: "{{ is_state('media_player.lg_webos_tv', 'on') }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.lg_webos_tv
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.lg_webos_tv