- platform: template
  sensors:
    home:
      friendly_name: 'Home'
      device_class: occupancy
      value_template: >-
          {{ is_state('person.sam', 'home')
             or is_state('person.ady', 'home') }}
    lounge_occupancy:
      friendly_name: 'Lounge Occupancy'
      device_class: occupancy
      delay_off:
        minutes: 10
      value_template: >-
          {{ is_state('binary_sensor.motion', 'on') }}
