- id: '1590219311319'
  alias: Home Assistant Boot
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      data:
        tag: start-up
      message: A system boot has been initiated at {{ states('sensor.time') }}
      title: Home Assistant Startup
    service: notify.mobile_app_sam_phone
  - condition: state
    entity_id: binary_sensor.home
    state: 'on'
  - service: alarm_control_panel.alarm_disarm
    data: {}
    entity_id: alarm_control_panel.alarm
  - wait_template: ''
    timeout: '10'
  - service: frontend.reload_themes
    data: {}
  - data:
      name: Clear
    service: frontend.set_theme
  - service: switch.turn_on
    data: {}
    entity_id: switch.extension_lead
  - service: switch.turn_on
    data: {}
    entity_id: switch.ikea_plug
  - service: switch.turn_on
    data: {}
    entity_id: switch.transmission_turtle_mode
  - service: switch.turn_off
    data: {}
    entity_id: switch.humidifier
  mode: restart
