- id: '1590219311319'
  alias: Home Assistant Boot
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - wait_template: ''
    timeout: '10'
    alias: Wait 10s
  - data:
      data:
        tag: start-up
      message: A system boot has been initiated at {{ states('sensor.time') }}
      title: Home Assistant Startup
    service: notify.mobile_app_sam_phone
  - condition: state
    entity_id: binary_sensor.home
    state: 'on'
  - service: alarm_control_panel.alarm_disarm
    data: {}
    entity_id: alarm_control_panel.alarm
  - service: frontend.reload_themes
    data: {}
  - data:
      name: clear
    service: frontend.set_theme
    enabled: false
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.extension_lead_2
  - service: switch.turn_off
    data: {}
    entity_id: switch.humidifier
  - service: script.enable_tv_on
    data: {}
  - service: mqtt.publish
    data:
      topic: monitor/office/KNOWN DEVICE STATES
  - service: mqtt.publish
    data:
      topic: monitor/bedroom/KNOWN DEVICE STATES
    enabled: false
  - service: mqtt.publish
    data:
      topic: monitor/lounge/KNOWN DEVICE STATES
  mode: restart
- id: '1650046822895'
  alias: Enable TV Turn On
  description: ''
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_tv
      webostv_mac: 78-5D-C8-92-EF-0B
- id: '1650834182234'
  alias: Re-enable TV turn on
  description: ''
  trigger:
  - platform: time_pattern
    hours: '1'
  condition: []
  action:
  - service: script.enable_tv_on
    data: {}
  mode: single
- id: '1671374342352'
  alias: Tag Computer is scanned
  description: ''
  triggers:
  - tag_id: computer
    trigger: tag
  conditions: []
  actions:
  - data: {}
    target:
      entity_id: switch.pc_power
    action: switch.turn_on
  - data:
      profile: relax
    target:
      entity_id: light.desk_lamp
    enabled: false
    action: light.turn_on
  mode: single
- id: '1720187794184'
  alias: Frigate Notifications (0.12.0.4a)
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.front_door
      notify_device: 0392f3b78fa57ea8933051b62331e81c
      base_url: https://home.samrenfrew.co.uk
      message: A {{ label | lower }} {{ 'is loitering' if loitering else 'was detected'
        }} at the front door
      update_thumbnail: true
      video: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4'
      icon: mdi:door-open
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
      button_1: Snapshot
      url_1: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
      button_2: Clip
      url_2: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{camera}}/clip.mp4'
      tv_duration: 0
      button_3: Silence
      group: Front Door
- id: '1728277713332'
  alias: Turn humidifier off after 1 hour
  description: ''
  triggers:
  - entity_id:
    - switch.humidifier
    to: 'on'
    from: 'off'
    trigger: state
  conditions: []
  actions:
  - action: script.turn_on
    target:
      entity_id: script.turn_off_after_x
    data:
      variables:
        entity: switch.humidifier
        minutes:
          '[object Object]':
  mode: single
- id: '1728327473723'
  alias: Clear Dining Room after 30 Mins
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.sonos_one
    from:
    to: paused
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions: []
  actions:
  - action: media_player.clear_playlist
    metadata: {}
    data: {}
    target:
      entity_id: media_player.sonos_one
  mode: single
- id: '1734637425851'
  alias: Turn on Humidifier every hour
  description: ''
  triggers:
  - trigger: time_pattern
    minutes: '0'
  conditions:
  - condition: time
    after: '20:00:00'
    before: 06:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.humidifier
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.humidifier
  mode: single
