- id: '1590219311319'
  alias: Home Assistant Boot
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - wait_template: ''
    timeout: '10'
    alias: Wait 10s
  - data:
      data:
        tag: start-up
      message: A system boot has been initiated at {{ states('sensor.time') }}
      title: Home Assistant Startup
    service: notify.mobile_app_sam_phone
  - condition: state
    entity_id: binary_sensor.home
    state: 'on'
  - service: alarm_control_panel.alarm_disarm
    data: {}
    entity_id: alarm_control_panel.alarm
  - service: frontend.reload_themes
    data: {}
  - data:
      name: clear
    service: frontend.set_theme
    enabled: false
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.extension_lead_2
  - service: switch.turn_off
    data: {}
    entity_id: switch.humidifier
  - service: script.enable_tv_on
    data: {}
  - service: mqtt.publish
    data:
      topic: monitor/office/KNOWN DEVICE STATES
  - service: mqtt.publish
    data:
      topic: monitor/bedroom/KNOWN DEVICE STATES
    enabled: false
  - service: mqtt.publish
    data:
      topic: monitor/lounge/KNOWN DEVICE STATES
  mode: restart
- id: '1633069327926'
  alias: Speedtest
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    hours: '*'
  condition: []
  action:
  - service: speedtestdotnet.speedtest
  mode: single
- id: '1650046822895'
  alias: Enable TV Turn On
  description: ''
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_tv
      webostv_mac: 78-5D-C8-92-EF-0B
- id: '1650834182234'
  alias: Re-enable TV turn on
  description: ''
  trigger:
  - platform: time_pattern
    hours: '1'
  condition: []
  action:
  - service: script.enable_tv_on
    data: {}
  mode: single
- id: '1665083371978'
  alias: Weekly Backup
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition:
  - condition: template
    value_template: '{{ now().isoweekday() == 7 }}'
    alias: On Sunday
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1667902499798'
  alias: Take The Bin Out
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.next_bin
    attribute: daysTo
    to: '1'
  condition:
  - condition: numeric_state
    entity_id: sensor.next_bin
    attribute: daysTo
    above: 0
    below: 2
    enabled: false
  action:
  - service: notify.mobile_app_sam_phone
    data:
      message: Take the {{ states("sensor.next_bin") }} out
      data:
        notification_icon: mdi:delete
        tag: bins
        color: green
        persistent: true
        sticky: true
        actions:
        - action: dismiss
          title: Dismiss
  - service: notify.google_assistant_sdk
    data:
      message: The {{ states("sensor.next_bin") }} needs to go out tonight
    enabled: true
  mode: single
- id: '1671374342352'
  alias: Tag Computer is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 'computer '
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.pc_power
  - service: light.turn_on
    data:
      profile: relax
    target:
      device_id: 2e0c7f0adf6f81d337d9058a82fd605f
    enabled: false
  mode: single
- id: '1704480730372'
  alias: Updated Bedroom Thermostat
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.bedroom_temperature
  condition: []
  action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: zigbee2mqtt/Bedroom Thermostat/set
      payload_template: '{"external_temperature_input":{{ (states(''sensor.bedroom_temperature'')|float(0)|round(1))
        }}}'
  mode: single
