blueprint:
  name: LG webOS Smart TV - Turn On Action
  description: "\n## LG webOS Smart TV - Turn On Action for 2022.2+\n\nThis blueprint\
    \ will run anytime the user turns the media player on through Home Assistant (UI\
    \ or service).\n\nAdding this blueprint will allow the user to turn on the LG\
    \ webOS TV through the UI after updating to HA 2022.2, without this blueprint\
    \ or similar automation the Turn On button won't be displayed due to a breaking\
    \ change. This is basically a shortcut to manually adding the automation described\
    \ in the [official documentation][1].\n\nThe default action is to send a Wake\
    \ On Lan magic packet in order to turn the TV on. Aditionally you can also setup\
    \ custom actions for alternate solutions such as: using an IR remote, turning\
    \ a smart socket on or calling an script. This is also useful for TV models connected\
    \ through Wireless that have issues with Wake on Lan.\n\n\n### Requirements:\n\
    - [LG webOS Smart TV][2] integration\n- [Wake On Lan][3] added to configuration.yaml\n\
    \n### Changelog:\n- 2022.02.03 - First release\n- 2022.02.06 - Custom actions\
    \ added\n  \n\n[1]: https://www.home-assistant.io/integrations/webostv/#turn-on-action\n\
    [2]: https://www.home-assistant.io/integrations/webostv/\n[3]: https://www.home-assistant.io/integrations/wake_on_lan/\n"
  domain: automation
  source_url: https://gist.github.com/cvroque/6780ca0869ef781e9de3b506fd501f78#file-webostv_turn_on-yaml
  input:
    webostv:
      name: LG webOS TV
      description: Select your media player entity
      selector:
        entity:
          domain: media_player
          integration: webostv
    webostv_mac:
      name: LG webOS TV MAC address
      description: The MAC address of the selected TV. You can get this information
        on your TV network settings or through your router.
      default: AA-BB-CC-DD-EE-FF
    select_action:
      name: Enable Custom Actions?
      description: When turned Off the default action is to send a magic packet, when
        turned On only the custom actions will run.
      default: false
      selector:
        boolean: {}
    custom_action:
      name: Custom Actions (Optional)
      description: When custom actions are enabled this automation will only perform
        the actions added here. Useful for TVs being turned on through an IR remote,
        script or similar.
      default: []
      selector:
        action: {}
variables:
  select_action: !input 'select_action'
trigger:
- platform: webostv.turn_on
  entity_id: !input 'webostv'
action:
- choose:
  - conditions:
    - '{{ select_action }}'
    sequence: !input 'custom_action'
  default:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: !input 'webostv_mac'
mode: queued
max_exceeded: silent
