# Green Bin
- trigger:
    - platform: calendar
      event: start
      offset: "-4:0:0"
      entity_id: calendar.bins
      enabled: true
    - platform: calendar
      event: end
      entity_id: calendar.bins
      enabled: true
    - platform: state
      entity_id:
        - calendar.bins
  binary_sensor:
    - name: Green Bin
      unique_id: green_bin
      icon: >
        {% if is_state("binary_sensor.green_bin", "on") %}
          mdi:delete-empty
        {% else %}
          mdi:delete
        {% endif %}
      state: >
        {% if trigger.event == "start" and 'Green Bin' in trigger.calendar_event.summary %}
          on
        {% elif is_state("calendar.bins", "on") and 'Green Bin' in state_attr("calendar.bins", "message") %}
          on
        {% else %}
          off
        {% endif %}

# Black Bin
- trigger:
    - platform: calendar
      event: start
      offset: "-4:0:0"
      entity_id: calendar.bins
      enabled: true
    - platform: calendar
      event: end
      entity_id: calendar.bins
      enabled: true
    - platform: state
      entity_id:
        - calendar.bins
  binary_sensor:
    - name: Black Bin
      unique_id: black_bin
      icon: >
        {% if is_state("binary_sensor.black_bin", "on") %}
          mdi:delete-empty
        {% else %}
          mdi:delete
        {% endif %}
      state: >
        {% if trigger.event == "start" and 'Black Bin' in trigger.calendar_event.summary %}
          on
        {% elif is_state("calendar.bins", "on") and 'Black Bin' in state_attr("calendar.bins", "message") %}
          on
        {% else %}
          off
        {% endif %}

# Brown Bin
- trigger:
    - platform: calendar
      event: start
      offset: "-4:0:0"
      entity_id: calendar.bins
      enabled: true
    - platform: calendar
      event: end
      entity_id: calendar.bins
      enabled: true
    - platform: state
      entity_id:
        - calendar.bins
  binary_sensor:
    - name: Brown Bin
      unique_id: brown_bin
      icon: mdi:delete
      state: >
        {% if trigger.event == "start" and 'Brown Bin' in trigger.calendar_event.summary %}
          on
        {% elif is_state("calendar.bins", "on") and 'Brown Bin' in state_attr("calendar.bins", "message") %}
          on
        {% else %}
          off
        {% endif %}

- binary_sensor:
  - name: 'home'
    unique_id: 'home_occupancy'
    device_class: occupancy
    state: >-
        {{ is_state('person.sam', 'home')
            or is_state('person.ady', 'home') }}

- binary_sensor:
  - name: 'home2'
    unique_id: 'home_occupancy2'
    device_class: occupancy
    state: >-
        {{ not is_state('input_select.sam_status_select', 'Out')
           or not is_state('input_select.ady_status_select', 'Out') }}


  # - name: 'lounge_occupancy'
  #   friendly_name: 'Lounge Occupancy'
  #   device_class: occupancy
  #   delay_off:
  #     minutes: 10
  #   value_template: >-
  #       {{ is_state('binary_sensor.lounge_motion', 'on') }}

- trigger:
    - platform: state
      entity_id: binary_sensor.home
  binary_sensor:
    - name: "home_10_minutes"
      unique_id: 'home_10_minutes'
      device_class: occupancy
      icon: mdi:clock-check-outline
      state: "{{ is_state('binary_sensor.home', 'on') }}"
      auto_off: 0:10:00

- trigger:
    - platform: state
      entity_id: binary_sensor.front_door
  binary_sensor:
    - name: "door_open_recently"
      unique_id: 'door_open_recently'
      device_class: door
      state: "{{ is_state('binary_sensor.front_door', 'on') }}"
      auto_off: 0:10:00

# - trigger:
#     - platform: state
#       entity_id: sensor.lounge_speaker_timers
#     - platform: state
#       entity_id: sensor.hallway_speaker_timers
#     - platform: state
#       entity_id: sensor.bedroom_speaker_timers
#   binary_sensor:
#     - name: "gh_timer_set"
#       unique_id: 'gh_timer_set'
#       state: >-
#         {{ not is_state('sensor.lounge_speaker_timers', 'unavailable')
#             or not is_state('sensor.hallway_speaker_timers', 'unavailable')
#             or not is_state('sensor.bedroom_speaker_timers', 'unavailable') }}

# - trigger:
#     - platform: state
#       entity_id: sensor.lounge_speaker_alarms
#     - platform: state
#       entity_id: sensor.hallway_speaker_alarms
#     - platform: state
#       entity_id: sensor.bedroom_speaker_alarms
#   binary_sensor:
#     - name: "gh_alarm_set"
#       unique_id: 'gh_alarm_set'
#       attributes:
#         friendly_name: "Alarm Set"
#       state: >-
#         {{ not is_state('sensor.lounge_speaker_alarms', 'unavailable')
#         or not is_state('sensor.hallway_speaker_alarms', 'unavailable')
#         or not is_state('sensor.bedroom_speaker_alarms', 'unavailable') }}