- platform: template
  lights:
    ikea_plug:
      unique_id: "ikea_plug"
      friendly_name: "Cool Lamp"
      value_template: "{{ is_state('switch.ikea_plug', 'on') }}"
      availability_template: "{{ is_state('switch.ikea_plug', 'on') or is_state('switch.ikea_plug', 'off')}}"
      turn_on:
        action: switch.turn_on
        entity_id: switch.ikea_plug
      turn_off:
        action: switch.turn_off
        entity_id: switch.ikea_plug
