- platform: template
  lights:
#    chair_lamp:
#      entity_id: switch.ikea_plug
#      friendly_name: "Chair Lamp"
#      value_template: "{{ is_state('switch.ikea_plug', 'on') }}"
#      turn_on:
#        service: switch.turn_on
#        entity_id: switch.ikea_plug
#      turn_off:
#        service: switch.turn_off
#        entity_id: switch.ikea_plug
    # shelf_lights:
    #   entity_id: switch.extension_lead
    #   value_template: "{{ is_state('switch.extension_lead', 'on') }}"
    #   turn_on:
    #     service: switch.turn_on
    #     entity_id: switch.extension_lead
    #   turn_off:
    #     service: switch.turn_off
    #     entity_id: switch.extension_lead
    christmas_tree:
      entity_id: switch.ikea_plug
      friendly_name: "Christmas Tree"
      value_template: "{{ is_state('switch.ikea_plug', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.ikea_plug
      turn_off:
        service: switch.turn_off
        entity_id: switch.ikea_plug
