  project_id: !secret ga_assistant
  expose_by_default: false
  service_account: !include service-account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - input_boolean
    - media_player
  entity_config:
    switch.extension_lead:
      expose: true
      name: Extension Lead
      room: Spare Room
    switch.humidifier:
      expose: true
      name: Humidifier
      room: Spare Room
      aliases:
        - Humidity
    # switch.ikea_plug:
    #   expose: true
    #   name: Spare Bedroom Plug
    #   room: Spare Room
    #   aliases:
    #     - Guest Plug
    #     - Makeup Plug
    switch.pc_power:
      expose: true
      name: Computer
      room: Spare Room
    switch.nas_power:
      expose: true
      name: Server
      room: Spare Room
    light.christmas_tree:
      expose: true
      name: Christmas Tree
      aliases:
        - Xmas Tree
        - Tree
      room: Lounge
    # light.shelf_lights:
    #   expose: true
    #   name: Office Lights
    #   aliases:
    #     - Grotto Lights
    #     - Spare Room Lights
    #   room: Spare Room
    light.chair_lamp:
      expose: true
      name: Chair Lamp
      aliases:
        - Other Lamp
        - Chair Light
        - Reading Light
      room: Lounge
    light.backlight:
      expose: true
      name: Backlight
      room: Lounge
    light.computer:
      expose: true
      name: Computer Light
      room: Spare Room
    light.big_lamp:
      expose: true
      name: Big Lamp
      room: Lounge
      aliases:
        - Big Lamp
        - Right Lamp
    light.small_lamp:
      expose: true
      name: TV Lamp
      room: Lounge
      aliases:
        - TV Lamp
        - Telly Lamp
        - Tele Lamp
    light.tv_lamp:
      expose: true
      name: Small Lamp
      room: Lounge
      aliases:
        - Small Lamp
        - Little Lamp
        - Left Lamp
    light.spotlight:
      expose: true
      name: Bedroom Light
      room: Bedroom
      aliases:
        - Spotlight
    media_player.tv:
      expose: true
      name: TV
      aliases:
        - TV
        - Telly
        - Television
        - Tele
      room: Lounge
    input_boolean.night_mode:
      expose: true
      name: Night Mode
      room: Flat
    input_boolean.guest_mode:
      expose: true
      name: Guest Mode
      room: Flat
