## PLANTS
  lounge:
    sensors:
      moisture: sensor.plant_moisture
      battery: sensor.plant_battery
      temperature: sensor.plant_temperature
      conductivity: sensor.plant_conductivity
      brightness: sensor.plant_brightness
    min_moisture: 20
    max_moisture: 40
    min_temperature: 10
    max_temperature: 30
    min_battery: 20
    min_conductivity: 50
