sensor:
  - state_topic: "monitor/office/ady_bt"
    value_template: "{{ value_json.confidence }}"
    unit_of_measurement: "%"
    state_class: "measurement"
    name: "Ady (BT) Office"
  - state_topic: "monitor/lounge/ady_bt"
    value_template: "{{ value_json.confidence }}"
    unit_of_measurement: "%"
    state_class: "measurement"
    name: "Ady (BT) Lounge"
  - state_topic: "monitor/office/sam_bt"
    value_template: "{{ value_json.confidence }}"
    unit_of_measurement: "%"
    state_class: "measurement"
    name: "Sam (BT) Office"
  - state_topic: "monitor/lounge/sam_bt"
    value_template: "{{ value_json.confidence }}"
    unit_of_measurement: "%"
    state_class: "measurement"
    name: "Sam (BT) Lounge"
