switch:
  - name: "Extension Lead"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: false
  - name: "Humidifier"
    state_topic: "stat/humidifier/POWER"
    command_topic: "cmnd/humidifier/power"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: false
