- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - precip_probability
    - precip_intensity
    - precip_intensity_max
    - temperature
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
  units: auto