- platform: mqtt
  state_topic: "sensor/node"
  name: "Lounge Light Level"
  unit_of_measurement: "lx"
  device_class: illuminance
  value_template: '{{ value_json.ldr }}'

# - platform: mqtt
#   state_topic: "sensor/node"
#   name: "Lounge Real Temperature"
#   unit_of_measurement: "°C"
#   device_class: temperature
#   value_template: >-
#       {%- if value_json.temperature|float > 1 -%}
#       {{ value_json.temperature | round(1) }}
#       {%- else -%}
#       nan
#       {%- endif -%}

- platform: mqtt
  state_topic: "sensor/node"
  name: "Lounge Temperature"
  unit_of_measurement: "°C"
  device_class: temperature
  value_template: >-
      {%- if value_json.heatIndex|float > 1 -%}
      {{ value_json.heatIndex | round(1) }}
      {%- else -%}
      nan
      {%- endif -%}

- platform: mqtt
  state_topic: "sensor/node"
  name: "Lounge Humidity"
  unit_of_measurement: "%"
  device_class: humidity
  value_template: >-
      {%- if value_json.humidity|float > 1 -%}
      {{ value_json.humidity | round(1) }}
      {%- else -%}
      nan
      {%- endif -%}
