- platform: template
  sensors:
    tplink_power:
      friendly_name: "TP-Link Power"
      unit_of_measurement: 'W'
      value_template: >-
          {{ state_attr('switch.tplink', 'current_power_w') }}
      device_class: power
    humidifier:
      friendly_name: "Humidifier"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'
      value_template: >-
          {%- if is_state('input_select.humidifier_location', 'Office') == true -%}
            {{ states('sensor.aq_1_humidity') }}
          {%- else -%}
            {{ states('sensor.lounge_humidity') }}
          {%- endif -%}
      device_class: humidity
