- platform: template
  sensors:
    humidifier:
      friendly_name: "Humidifier"
      icon_template: mdi:water-percent
      unit_of_measurement: '%'
      value_template: >-
          {%- if is_state('input_select.humidifier_location', 'Office') == true -%}
            {{ states('sensor.aq_1_humidity') }}
          {%- else -%}
            {{ states('sensor.lounge_humidity') }}
          {%- endif -%}
      device_class: humidity
